services:
  postgres:
    image: postgres:latest
    container_name: heatmap_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: heatmap
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - $PWD/sql:/sql

volumes:
  pgdata:
