// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package model

type Entry struct {
	ID        int64
	EntryDate int64
	HabitID   int64
}

type Habit struct {
	ID        int64
	Name      string
	CreatedAt int64
}
