// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package model

import (
	"time"
)

type Entry struct {
	ID        int64
	EntryDate string
	HabitID   int64
}

type Habit struct {
	ID        int64
	Name      string
	CreatedAt int64
}

type User struct {
	ID             int64
	Name           string
	Email          string
	HashedPassword string
	CreatedAt      time.Time
}
