// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package model

type Entry struct {
	ID        int64
	EntryDate string
	HabitID   int64
}

type Habit struct {
	ID        int64
	Name      string
	CreatedAt int64
}
